FROM node:24-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:24-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
EXPOSE 3001
CMD ["npx", "serve", "-s", "dist", "-l", "3001"]
